tarantool:
  image: tarantool/tarantool:1.6
  volumes:
    - ./lua:/opt/tarantool/lua
    - ./share:/share
  volumes_from:
    - tarantool-data
  command: /usr/local/bin/tarantool /opt/tarantool/lua/boot.lua

tarantool-data:
  image: busybox
  volumes:
    - /data